spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # local docker db
    url: ENC(C8mQIxqkszJ7rWFSeKKfGP3W8iwWo8KhwezyapCKM8KFX6Qqu6nOGMCZz9Tj6MZAJIRTAbDcmyk53r/STiluTudDB26GWRCh)
    username: ENC(rFf0u7UY0IzEwjlSK69n6vxN8XFimQSz/PHtPlTJvJw=)
    password: ENC(YhRb7Zms40OH2hFdgqN1Pj0bkNR5Ur/9mwc9XO8cyG8=)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    #JPA보다 flyway 우선 실행
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  mail:
    host: smtp.gmail.com
    username: ENC(dloOCGPjxlxKngYlHBslBYlFSsijoaqGoWaLO4SH0m3V0GEstBMpNA==)
    password: ENC(GwgkC7z/p3rZf+t9C2x+6lSUu8DBLFISPrTAzBpy45OjmvLBtBN6Pw==)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
      host: localhost
      password: ENC(MXs+zde03lvI/DwZa/0vENxrJOBHzmWJPs2BYb5n/4Z2iEpqEovfzQ==)

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

logging:
  file:
    path: ./logs/api/
    name: local-api-log
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 50MB
      total-size-cap: 5GB

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
  endpoint:
    health:
      show-details: never

constants:
  host-url: "http://localhost:3000"
  password-reset-token:
    duration-minute: 5
  jwt:
    secret: V2FzaEZpdC1Qcm9qZWN0LURlc2lnbmVkLUJ5LUtlcm5lbDM2MC1UZWFtLVdhc2hGaXQtQmVzdA== # Base64 Encoded
    access-token-expiration-minutes: 30
    refresh-token-expiration-days: 7


aws:
  credentials:
    access-key-id: ENC(dloOCGPjxlxKngYlHBslBYlFSsijoaqGoWaLO4SH0m3V0GEstBMpNA==)
    secret-access-key: ENC(dloOCGPjxlxKngYlHBslBYlFSsijoaqGoWaLO4SH0m3V0GEstBMpNA==)
  s3:
    bucket:
      name: ENC(dloOCGPjxlxKngYlHBslBYlFSsijoaqGoWaLO4SH0m3V0GEstBMpNA==)
      url: ENC(dloOCGPjxlxKngYlHBslBYlFSsijoaqGoWaLO4SH0m3V0GEstBMpNA==)